/**
 * Invidious API response shapes.
 * Field names mirror the Invidious REST API exactly (snake_case where the API uses it)
 * so responses can be consumed without a translation layer.
 */

export interface ImageRef {
  url: string
  width: number
  height: number
  quality?: string
}

/** A muxed progressive stream (video+audio in one file). Quality ceiling is typically 360p/720p. */
export interface FormatStream {
  url: string
  itag: string
  type: string
  quality: string
  container?: string
  encoding?: string
  qualityLabel?: string
  resolution?: string
  size?: string
  fps?: number
  bitrate?: string
}

/** A DASH representation: video-only OR audio-only, never both. */
export interface AdaptiveFormat {
  url: string
  itag: string
  type: string
  bitrate: string
  init?: string
  index?: string
  clen?: string
  lmt?: string
  projectionType?: string
  container?: string
  encoding?: string
  /** Video-only fields */
  qualityLabel?: string
  resolution?: string
  fps?: number
  /** Audio-only fields */
  audioQuality?: string
  audioSampleRate?: number
  audioChannels?: number
  /** Present on dubbed/localized audio tracks. */
  audioTrack?: {
    id?: string
    displayName?: string
    audioIsDefault?: boolean
  }
}

export interface Caption {
  label: string
  language_code: string
  url: string
}

/** Sprite sheets used for seek-bar previews. */
export interface Storyboard {
  url: string
  templateUrl?: string
  width: number
  height: number
  count: number
  interval: number
  storyboardWidth: number
  storyboardHeight: number
  storyboardCount: number
}

export interface VideoDetails {
  type: 'video'
  title: string
  videoId: string
  videoThumbnails: ImageRef[]
  storyboards?: Storyboard[]
  description: string
  descriptionHtml: string
  published: number
  publishedText: string
  keywords?: string[]
  viewCount: number
  likeCount: number
  dislikeCount: number
  paid: boolean
  premium: boolean
  isFamilyFriendly: boolean
  allowedRegions?: string[]
  genre?: string
  genreUrl?: string
  author: string
  authorId: string
  authorUrl: string
  authorThumbnails?: ImageRef[]
  subCountText?: string
  lengthSeconds: number
  allowRatings: boolean
  rating: number
  isListed: boolean
  liveNow: boolean
  isPostLiveDvr?: boolean
  isUpcoming: boolean
  premiereTimestamp?: number
  dashUrl?: string
  hlsUrl?: string
  /**
   * A DASH manifest generated by the app rather than fetched from a server.
   *
   * The direct YouTube backend has no instance to request a manifest from, and the IOS
   * client returns no progressive formats at all, so adaptive playback depends on
   * building an MPD from adaptiveFormats. The player turns this into a blob URL.
   */
  dashManifestXml?: string
  adaptiveFormats: AdaptiveFormat[]
  formatStreams: FormatStream[]
  captions: Caption[]
  recommendedVideos: VideoSummary[]
}

/** The condensed video object returned inside feeds, search results and channel listings. */
export interface VideoSummary {
  type: 'video' | 'shortVideo'
  title: string
  videoId: string
  author: string
  authorId: string
  authorUrl?: string
  videoThumbnails: ImageRef[]
  description?: string
  descriptionHtml?: string
  viewCount: number
  viewCountText?: string
  published?: number
  publishedText?: string
  lengthSeconds: number
  liveNow?: boolean
  premium?: boolean
  isUpcoming?: boolean
  premiereTimestamp?: number
}

export interface ChannelSummary {
  type: 'channel'
  author: string
  authorId: string
  authorUrl: string
  authorThumbnails: ImageRef[]
  autoGenerated?: boolean
  subCount: number
  videoCount: number
  description?: string
  descriptionHtml?: string
}

export interface ChannelDetails extends ChannelSummary {
  authorBanners: ImageRef[]
  totalViews?: number
  joined?: number
  isFamilyFriendly?: boolean
  allowedRegions?: string[]
  tabs?: string[]
  latestVideos?: VideoSummary[]
  relatedChannels?: ChannelSummary[]
}

export interface PlaylistSummary {
  type: 'playlist'
  title: string
  playlistId: string
  author: string
  authorId: string
  authorUrl?: string
  playlistThumbnail?: string
  videoCount: number
  videos?: VideoSummary[]
}

export interface PlaylistDetails extends PlaylistSummary {
  description?: string
  descriptionHtml?: string
  viewCount?: number
  updated?: number
  isListed?: boolean
  videos: VideoSummary[]
}

export type SearchResult = VideoSummary | ChannelSummary | PlaylistSummary

export interface Comment {
  author: string
  authorThumbnails: ImageRef[]
  authorId: string
  authorUrl: string
  isEdited: boolean
  isPinned?: boolean
  content: string
  contentHtml: string
  published: number
  publishedText: string
  likeCount: number
  commentId: string
  authorIsChannelOwner: boolean
  creatorHeart?: { creatorThumbnail: string; creatorName: string }
  replies?: { replyCount: number; continuation: string }
}

export interface CommentsResponse {
  commentCount?: number
  videoId: string
  comments: Comment[]
  continuation?: string
}

/** Categories and skip behaviour as shipped in sponsorblock_config.json. */
export type SponsorBlockCategory =
  | 'sponsor' | 'selfpromo' | 'interaction' | 'poi_highlight' | 'intro'
  | 'outro' | 'preview' | 'hook' | 'filler' | 'music_offtopic'

export type SponsorBlockOption = 'auto_skip' | 'manual_skip' | 'show_in_seekbar' | 'disable'

export interface SponsorBlockSegment {
  category: SponsorBlockCategory
  actionType: 'skip' | 'mute' | 'full' | 'poi'
  segment: [number, number]
  UUID: string
  videoDuration: number
  locked: number
  votes: number
  description: string
}
